### ISSUE TITLE
Support for `message` option

### ISSUE THREAD

**Issue by LRNZ09** [talut/rn-actionsheet-module#1]
`ActionSheetIOS` support a `message` option, which is a string displayed below the title.
This would be great if ported to Android too.

**Comment by talut** [comment]
Hey, thanks for issue. Yes I'll update package for ios. Also I will look at material.io/design for  best practice. If message is best practice I'll add.

**Comment by talut** [comment]
@LRNZ09 Hi, I added to message props to package. But this props will only work for IOS 'cause I searched BottomSheetDialog and I saw only title is acceptable. So you can use message props for IOS with v0.2.3. Have a great day.
