### ISSUE TITLE
Support Light | Dark theme or allow to custom background color

### ISSUE THREAD

**Issue by sanghavan** [talut/rn-actionsheet-module#10]
This is feature request.
May this lib support Light | Dark theme or allow to custom background color?

**Comment by talut** [comment]
Hi, sorry for late answer. Currently I don't have any time for this feature. But if I have I'll add.

**Comment by talut** [comment]
tintColor & backgroundColor added for android. Dark support already exist for IOS. Please check new version v1.0.4
